
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers';
import { jwtVerify } from 'jose';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const secretKey = new TextEncoder().encode(
  process.env.JWT_SECRET || 'fallback_secret_for_development_only_12345'
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AngeBingo",
  description: "Generated by angebingo",
};

export default async function RootLayout({ children }) {
  // Server-side user extraction
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get('session')?.value;
  let user = null;
  if (sessionToken) {
    try {
      const { payload } = await jwtVerify(sessionToken, secretKey);
      user = payload;
    } catch (error) {
      console.error("Invalid token:", error);
    }
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-950 text-white selection:bg-fuchsia-500 selection:text-white font-sans overflow-x-hidden">
        <Navbar user={user} />
        <main className="flex-1 flex flex-col">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
